FEATURE_CONFIG = {
    # اندیکاتورهای کلاسیک و میانگین‌ها
    "ema5": True,
    "ema9": True,
    "ema10": True,
    "ema20": True,
    "ema21": True,
    "ema50": True,
    "ema100": True,
    "ema200": True,
    "sma20": True,
    "sma50": True,
    "tema20": True,
    "rsi14": True,
    "atr14": True,
    "macd": True,
    "macd_signal": True,
    "macd_hist": True,
    "bb_upper": True,
    "bb_lower": True,
    "bb_width": True,
    "obv": True,
    "vwap": True,
    "stoch_k": True,
    "stoch_d": True,
    "cci": True,
    "willr": True,
    "roc": True,
    "psar": True,
    "candle_change": True,
    "candle_range": True,
    "volume_mean": True,
    "volume_spike": True,
    "close": True,
    "open": True,
    "high": True,
    "low": True,
    "volume": True,
    # اندیکاتورهای مدرن، آماری و پرایس اکشن
    "adx14": True,
    "supertrend": True,
    "donchian_high": True,
    "donchian_low": True,
    "momentum5": True,
    "momentum10": True,
    "mean_reversion_zscore": True,
    "williams_vix_fix": True,
    "volatility": True,
    "price_gap": True,
    "shadow_ratio": True,
    "green_candles_10": True,
    "red_candles_10": True,
    # فیچرهای پیشرفته ورود/خروج
    "ema_cross_9_21": True,
    "breakout_30": True,
    "breakdown_30": True,
    "green_candle_ratio_20": True,
    "red_candle_ratio_20": True,
    "price_ema50_diff": True,
    "price_ema200_diff": True,
    "vol_spike": True,
    "atr_spike": True,
    "wick_ratio": True,
    # کندل پترن‌ها
    "engulfing": True,
    "hammer": True,
    "doji": True,
    "morning_star": True,
    "shooting_star": True,
    # فیچرهای خبری و فاندامنتال
    "news_sentiment_mean_6h": True,
    "news_shock_count_6h": True,
    "news_count": True,
    "news_sentiment_mean": True,
    "news_sentiment_std": True,
    "news_pos_count": True,
    "news_neg_count": True,
    "news_latest_sentiment": True,
    "news_content_len": True,
    "news_weighted_score": True,
    # دیگر فیچرهای خبری بر اساس تایم‌فریم (در صورت نیاز اضافه کن)
}