FEATURE_CONFIG = {
    "ema5": True,
    "ema10": True,
    "ema20": True,
    "ema50": True,
    "ema100": True,
    "ema200": True,
    "sma20": True,
    "sma50": True,
    "tema20": True,
    "rsi14": True,
    "atr14": True,
    "macd": True,
    "macd_signal": True,
    "macd_hist": True,
    "bb_upper": True,
    "bb_lower": True,
    "bb_width": True,
    "obv": True,
    "vwap": True,
    "stoch_k": True,
    "stoch_d": True,
    "cci": True,
    "willr": True,
    "roc": True,
    "psar": True,
    "candle_change": True,
    "candle_range": True,
    "volume_mean": True,
    "volume_spike": True,
    "close": True,
    "open": True,
    "high": True,
    "low": True,
    "volume": True,
    # فیچرهای مدرن و آماری و پرایس اکشن
    "adx14": True,
    "supertrend": True,
    "donchian_high": True,
    "donchian_low": True,
    "momentum5": True,
    "momentum10": True,
    "mean_reversion_zscore": True,
    "williams_vix_fix": True,
    "volatility": True,
    "price_gap": True,
    "shadow_ratio": True,
    "green_candles_10": True,
    "red_candles_10": True,
    # کندل پترن‌ها (نمونه، بقیه را اضافه کن)
    "engulfing": True,
    "hammer": True,
    "doji": True,
    "morning_star": True,
    "shooting_star": True,
    # ... اگر خواستی بقیه talib پترن‌ها را هم اضافه کن
}
